### ISSUE TITLE
New release to update readme on DUB registry

### ISSUE THREAD

**Issue by dkorpel** [ShigekiKarita/d-graphviz#1]
There was an error in the readme (`import dot;` instead of `import dgraphviz`;) that is corrected on master, but the [DUB registry](http://code.dlang.org/packages/d-graphviz) shows the 0.0.1 version which has the outdated example. Can you please release a new version so it's fixed?

**Comment by ShigekiKarita** [comment]
Sorry for late. I will merge your PR soon. Then release a new version!

**Comment by ShigekiKarita** [comment]
It seems to be fixed. https://code.dlang.org/packages/d-graphviz
